-- Tables creation
CREATE TABLE "EMPLOYEE_GAR" (
	"EMP_ID" INT NOT NULL,
	"ODD_WEEK_OFFICE_ID" INT NOT NULL,
	"EVEN_WEEK_OFFICE_ID" INT NOT NULL,
	"LAST_NAME" VARCHAR2(255) NOT NULL,
	"FIRST_NAME" VARCHAR2(255) NOT NULL,
	"EMAIL" VARCHAR2(255) NOT NULL,
	"JOB_TITLE" VARCHAR2(50) NOT NULL,
	CONSTRAINT EMPLOYEE_GAR_PK PRIMARY KEY ("EMP_ID"));


CREATE TABLE "OFFICE_GAR" (
	"CODE" INT NOT NULL,
	"CITY" VARCHAR2(255) NOT NULL,
	"PHONE" VARCHAR2(255) NOT NULL,
	"ADDRESS" VARCHAR2(255) NOT NULL,
	"COUNTRY" VARCHAR2(255) NOT NULL,
	CONSTRAINT OFFICE_GAR_PK PRIMARY KEY ("CODE"));


CREATE TABLE "CUSTOMER_GAR" (
	"CUST_ID" INT NOT NULL,
	"SALES_EMP_ID" INT NOT NULL,
	"LAST_NAME" VARCHAR2(255),
	"FIRST_NAME" VARCHAR2(255),
	"PHONE" VARCHAR2(20),
	"ADDRESS" VARCHAR2(255),
	"EMAIL" VARCHAR2(255) UNIQUE,
	CONSTRAINT CUSTOMER_GAR_PK PRIMARY KEY ("CUST_ID"));


CREATE TABLE "PAYMENT_GAR" (
	"BANK_NAME" VARCHAR2(255) NOT NULL,
	"PAY_CUST_ID" INT NOT NULL,
	"PAY_METHOD" VARCHAR2(20) NOT NULL,
	"PAYMENT_DATE" DATE NOT NULL,
	"AMOUNT" NUMERIC NOT NULL);


CREATE TABLE "BANK_GAR" (
	"BANK_NAME" VARCHAR2(20),
	"SWIFT_CODE" VARCHAR2(8) NOT NULL,
	"COMISSION" FLOAT NOT NULL,
	CONSTRAINT BANK_GAR_PK PRIMARY KEY ("BANK_NAME"));


CREATE TABLE "ORDER_GAR" (
	"ORDER_ID" INT NOT NULL,
	"CUST_ID" INT NOT NULL,
	"ORDER_DATE" DATE NOT NULL,
	"REQUIRED_DATE" DATE NOT NULL,
	"STATUS" VARCHAR2(255) NOT NULL,
	CONSTRAINT ORDER_GAR_PK PRIMARY KEY ("ORDER_ID"));

-- Adding constraints

ALTER TABLE "EMPLOYEE_GAR" ADD CONSTRAINT "EMPLOYEE_GAR_FK0" FOREIGN KEY ("ODD_WEEK_OFFICE_ID") REFERENCES "OFFICE_GAR"("CODE");
ALTER TABLE "EMPLOYEE_GAR" ADD CONSTRAINT "EMPLOYEE_GAR_FK1" FOREIGN KEY ("EVEN_WEEK_OFFICE_ID") REFERENCES "OFFICE_GAR"("CODE");
ALTER TABLE "CUSTOMER_GAR" ADD CONSTRAINT "CUSTOMER_GAR_FK0" FOREIGN KEY ("SALES_EMP_ID") REFERENCES "EMPLOYEE_GAR"("EMP_ID");
ALTER TABLE "PAYMENT_GAR" ADD CONSTRAINT "PAYMENT_GAR_FK0" FOREIGN KEY ("BANK_NAME") REFERENCES "BANK_GAR"("BANK_NAME");
ALTER TABLE "PAYMENT_GAR" ADD CONSTRAINT "PAYMENT_GAR_FK1" FOREIGN KEY ("PAY_CUST_ID") REFERENCES "CUSTOMER_GAR"("CUST_ID");
ALTER TABLE "ORDER_GAR" ADD CONSTRAINT "ORDER_GAR_FK0" FOREIGN KEY ("CUST_ID") REFERENCES "CUSTOMER_GAR"("CUST_ID");

-- Inserting data
    
-- Into BANK_GAR
INSERT ALL
   INTO BANK_GAR (BANK_NAME, SWIFT_CODE, COMISSION) VALUES ('BRD', 'BRDEROBU', 0.1)
   INTO BANK_GAR (BANK_NAME, SWIFT_CODE, COMISSION) VALUES ('ALPHA BANK', 'ALBPROBU', 0.2)
   INTO BANK_GAR (BANK_NAME, SWIFT_CODE, COMISSION) VALUES ('BANC POST S.A.', 'BPOSROBU', 0.3)
   INTO BANK_GAR (BANK_NAME, SWIFT_CODE, COMISSION) VALUES ('BCR', 'RNCBROBU', 0.05)
   INTO BANK_GAR (BANK_NAME, SWIFT_CODE, COMISSION) VALUES ('BT', 'BTRLROBU', 0.0)
   INTO BANK_GAR (BANK_NAME, SWIFT_CODE, COMISSION) VALUES ('BR', 'BRMAROBU', 0.25)
   INTO BANK_GAR (BANK_NAME, SWIFT_CODE, COMISSION) VALUES ('BANK OF CYPRUS', 'BCYPROBU', 0.35)
   INTO BANK_GAR (BANK_NAME, SWIFT_CODE, COMISSION) VALUES ('CEC BANK', 'CECEROBU', 0.1)
   INTO BANK_GAR (BANK_NAME, SWIFT_CODE, COMISSION) VALUES ('CTIBANK', 'CITIROBU', 0.2)
   INTO BANK_GAR (BANK_NAME, SWIFT_CODE, COMISSION) VALUES ('BANK LEUMI', 'DAFBROBU', 0.15)
		-- If client buys cash 
		INTO BANK_GAR (BANK_NAME, SWIFT_CODE, COMISSION) VALUES ('NO BANK', '00000000', 0.0)
SELECT 1 FROM DUAL;

-- Into OFFICE_GAR
INSERT ALL
    INTO OFFICE_GAR (CODE, CITY, PHONE, ADDRESS, COUNTRY)
            VALUES (1, 'BUDAPESTA', '10745566981', 'ORHIDEEA STREET', 'HUNGARY')
    INTO OFFICE_GAR (CODE, CITY, PHONE, ADDRESS, COUNTRY)
            VALUES (2, 'ATHENS', '20745566982', 'ANTIGONIS STREET', 'GREECE')
    INTO OFFICE_GAR (CODE, CITY, PHONE, ADDRESS, COUNTRY)
            VALUES (3, 'MOSCOW', '30745566983', 'KOLOKOTRONI STREET', 'RUSSIA')
    INTO OFFICE_GAR (CODE, CITY, PHONE, ADDRESS, COUNTRY)
            VALUES (4, 'BUCHAREST', '40745566984', '1ST DECEMBER 1918 STREET', 'ROMANIA')
    INTO OFFICE_GAR (CODE, CITY, PHONE, ADDRESS, COUNTRY)
            VALUES (5, 'BERLIN', '50745566985', 'LEGIENDAMM', 'GERMANY')
    INTO OFFICE_GAR (CODE, CITY, PHONE, ADDRESS, COUNTRY)
            VALUES (6, 'PARIS', '10743766186', 'LA VIOLET STREET', 'FRANCE')
    INTO OFFICE_GAR (CODE, CITY, PHONE, ADDRESS, COUNTRY)
            VALUES (7, 'MADRID', '40747366987', 'SERRATE STREET', 'SPAIN')
    INTO OFFICE_GAR (CODE, CITY, PHONE, ADDRESS, COUNTRY)
            VALUES (8, 'ROME', '70745123988', 'EL PIZZERRIE STREET', 'ITALY')
    INTO OFFICE_GAR (CODE, CITY, PHONE, ADDRESS, COUNTRY)
            VALUES (9, 'LONDON', '207454278989', 'VICTORY STREET', 'GREAT BRITAIN')
    INTO OFFICE_GAR (CODE, CITY, PHONE, ADDRESS, COUNTRY)
            VALUES (10, 'KIEV', '80745258910', 'KRAKATUN STREET', 'UKRAINE')
SELECT 1 FROM DUAL;

-- Into EMPLOYEE_GAR
INSERT ALL
    INTO EMPLOYEE_GAR (EMP_ID, ODD_WEEK_OFFICE_ID, EVEN_WEEK_OFFICE_ID, LAST_NAME, FIRST_NAME, EMAIL, JOB_TITLE)
        VALUES (1, 3, 1, 'SMITH', 'JHON', 'JHON@GMAIL.COM', 'SELLER')
    INTO EMPLOYEE_GAR (EMP_ID, ODD_WEEK_OFFICE_ID, EVEN_WEEK_OFFICE_ID, LAST_NAME, FIRST_NAME, EMAIL, JOB_TITLE)
        VALUES (2, 2, 3, 'ALLAN', 'KERRY', 'ALLAN@GMAIL.COM', 'MANAGER')
    INTO EMPLOYEE_GAR (EMP_ID, ODD_WEEK_OFFICE_ID, EVEN_WEEK_OFFICE_ID, LAST_NAME, FIRST_NAME, EMAIL, JOB_TITLE)
        VALUES (3, 2, 8, 'JELLY', 'YOU', 'JELLY@GMAIL.COM', 'SELLER')
    INTO EMPLOYEE_GAR (EMP_ID, ODD_WEEK_OFFICE_ID, EVEN_WEEK_OFFICE_ID, LAST_NAME, FIRST_NAME, EMAIL, JOB_TITLE)
        VALUES (4, 1, 9, 'MERTY', 'KLAUS', 'MERTY@GMAIL.COM', 'CEO')
    INTO EMPLOYEE_GAR (EMP_ID, ODD_WEEK_OFFICE_ID, EVEN_WEEK_OFFICE_ID, LAST_NAME, FIRST_NAME, EMAIL, JOB_TITLE)
        VALUES (5, 3, 6, 'TRENY', 'DAN', 'TRENY@GMAIL.COM', 'SELLER')
    INTO EMPLOYEE_GAR (EMP_ID, ODD_WEEK_OFFICE_ID, EVEN_WEEK_OFFICE_ID, LAST_NAME, FIRST_NAME, EMAIL, JOB_TITLE)
        VALUES (6, 4, 5, 'JAMES', 'ROBER', 'JAMESRB@YAHOO.COM', 'SELLER')
    INTO EMPLOYEE_GAR (EMP_ID, ODD_WEEK_OFFICE_ID, EVEN_WEEK_OFFICE_ID, LAST_NAME, FIRST_NAME, EMAIL, JOB_TITLE)
        VALUES (7, 7, 6, 'MICHAEL', 'WILLIAM', 'WILLMICHA@GMAIL.COM', 'MANAGER')
    INTO EMPLOYEE_GAR (EMP_ID, ODD_WEEK_OFFICE_ID, EVEN_WEEK_OFFICE_ID, LAST_NAME, FIRST_NAME, EMAIL, JOB_TITLE)
        VALUES (8, 5, 8, 'DAVID', 'RICHARD', 'DAVARD@OUTLOOK.COM', 'SELLER')
    INTO EMPLOYEE_GAR (EMP_ID, ODD_WEEK_OFFICE_ID, EVEN_WEEK_OFFICE_ID, LAST_NAME, FIRST_NAME, EMAIL, JOB_TITLE)
        VALUES (9, 3, 9, 'JOSEPH', 'THOMAS', 'JSPHTOM@GMAIL.COM', 'CEO')
    INTO EMPLOYEE_GAR (EMP_ID, ODD_WEEK_OFFICE_ID, EVEN_WEEK_OFFICE_ID, LAST_NAME, FIRST_NAME, EMAIL, JOB_TITLE)
        VALUES (10, 10, 6, 'DANIEL', 'ANTHONY', 'DANITONY@YAHOO.COM', 'SELLER')
SELECT 1 FROM DUAL;

-- Into CUSTOMER_GAR
INSERT ALL
    INTO CUSTOMER_GAR (CUST_ID, SALES_EMP_ID, LAST_NAME, FIRST_NAME, PHONE, ADDRESS, EMAIL)
        VALUES (1, 2, 'SMITH', 'KATE', '14087859131', 'AVENUE OF THE ARMY', 'SMITHKATE@GMAIL.COM')
    INTO CUSTOMER_GAR (CUST_ID, SALES_EMP_ID, LAST_NAME, FIRST_NAME, PHONE, ADDRESS, EMAIL)
        VALUES (2, 4, 'ALLAN', 'JHON', '02071839232', 'DEVONSHIRE STREET', 'ALLANJH@GMAIL.COM')
    INTO CUSTOMER_GAR (CUST_ID, SALES_EMP_ID, LAST_NAME, FIRST_NAME, PHONE, ADDRESS, EMAIL)
        VALUES (3, 1, 'MERELY', 'JOSH', '14087859333', 'ST. JOHN STREET',  'MERJOSH@GMAIL.COM')
    INTO CUSTOMER_GAR (CUST_ID, SALES_EMP_ID, LAST_NAME, FIRST_NAME, PHONE, ADDRESS, EMAIL)
        VALUES (4, 3, 'POPA', 'ALIN', '40748599330', 'ORHIDEEA STREET',  'ALINPOPA@GMAIL.COM')
SELECT 1 FROM DUAL;

-- Into PAYMENT_GAR
INSERT ALL
    INTO PAYMENT_GAR (BANK_NAME, PAY_CUST_ID, PAY_METHOD, PAYMENT_DATE, AMOUNT)
        VALUES ('BRD', 1, 'CARD', TO_DATE('2020-06-02','YYYY-MM-DD'), 15)
    INTO PAYMENT_GAR (BANK_NAME, PAY_CUST_ID, PAY_METHOD, PAYMENT_DATE, AMOUNT)
        VALUES ('CTIBANK', 2, 'CARD', TO_DATE('2020-06-03','YYYY-MM-DD'), 5)
    INTO PAYMENT_GAR (BANK_NAME, PAY_CUST_ID, PAY_METHOD, PAYMENT_DATE, AMOUNT)
        VALUES ('BCR', 3, 'CARD', TO_DATE('2020-06-03','YYYY-MM-DD'), 35)
    INTO PAYMENT_GAR (BANK_NAME, PAY_CUST_ID, PAY_METHOD, PAYMENT_DATE, AMOUNT)
        VALUES ('BT', 2, 'CARD', TO_DATE('2020-06-04','YYYY-MM-DD'), 23)
    INTO PAYMENT_GAR (BANK_NAME, PAY_CUST_ID, PAY_METHOD, PAYMENT_DATE, AMOUNT)
        VALUES ('BRD', 4, 'CARD', TO_DATE('2020-06-05','YYYY-MM-DD'), 12)
    INTO PAYMENT_GAR (BANK_NAME, PAY_CUST_ID, PAY_METHOD, PAYMENT_DATE, AMOUNT)
        VALUES ('ALPHA BANK', 1, 'CARD',TO_DATE('2020-06-07','YYYY-MM-DD'), 37)
    INTO PAYMENT_GAR (BANK_NAME, PAY_CUST_ID, PAY_METHOD, PAYMENT_DATE, AMOUNT)
        VALUES ('BR', 3, 'CARD', TO_DATE('2020-06-09','YYYY-MM-DD'), 19)
SELECT 1 FROM DUAL;

-- Into ORDER_GAR
INSERT ALL
    INTO ORDER_GAR  (ORDER_ID, CUST_ID, ORDER_DATE, REQUIRED_DATE, STATUS)
        VALUES (1, 2, TO_DATE('2020-05-02','YYYY-MM-DD'), TO_DATE('2020-05-05','YYYY-MM-DD'), 'SHIPPING')
    INTO ORDER_GAR  (ORDER_ID, CUST_ID, ORDER_DATE, REQUIRED_DATE, STATUS)
        VALUES (2, 1, TO_DATE('2020-06-03','YYYY-MM-DD'), TO_DATE('2020-06-08','YYYY-MM-DD'), 'SHIPPING')
    INTO ORDER_GAR  (ORDER_ID, CUST_ID, ORDER_DATE, REQUIRED_DATE, STATUS)
        VALUES (3, 3,TO_DATE('2020-05-07','YYYY-MM-DD'), TO_DATE('2020-05-11','YYYY-MM-DD'), 'DELIVERED')
    INTO ORDER_GAR  (ORDER_ID, CUST_ID, ORDER_DATE, REQUIRED_DATE, STATUS)
        VALUES (4, 2, TO_DATE('2020-05-19','YYYY-MM-DD'),TO_DATE('2020-05-21','YYYY-MM-DD'), 'SHIPPING')
    INTO ORDER_GAR  (ORDER_ID, CUST_ID, ORDER_DATE, REQUIRED_DATE, STATUS)
        VALUES (5, 4,TO_DATE('2020-06-04','YYYY-MM-DD'), TO_DATE('2020-06-09','YYYY-MM-DD'), 'DELIVERED')
SELECT 1 FROM DUAL;


